CREATE TABLE [dbo].[PAQUETE]
(
[IDPAQUETE] [int] NOT NULL,
[IDCIUDAD] [int] NOT NULL,
[IDREPARTIDOR] [int] NOT NULL,
[CODIGOPAQ] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCRIPCIONPAQ] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESTINATARIOPAQ] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAQUETE] ADD CONSTRAINT [PK_PAQUETE] PRIMARY KEY CLUSTERED  ([IDPAQUETE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [DESTINO_FK] ON [dbo].[PAQUETE] ([IDCIUDAD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [DISTRIBUYE_FK] ON [dbo].[PAQUETE] ([IDREPARTIDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAQUETE] ADD CONSTRAINT [FK_PAQUETE_DESTINO_CIUDAD] FOREIGN KEY ([IDCIUDAD]) REFERENCES [dbo].[CIUDAD] ([IDCIUDAD])
GO
ALTER TABLE [dbo].[PAQUETE] ADD CONSTRAINT [FK_PAQUETE_DISTRIBUY_REPARTID] FOREIGN KEY ([IDREPARTIDOR]) REFERENCES [dbo].[REPARTIDOR] ([IDREPARTIDOR])
GO
