CREATE TABLE [dbo].[REPARTIDOR]
(
[IDREPARTIDOR] [int] NOT NULL,
[NOMBRESREP] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APELLIDOSREP] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CEDULAREP] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONOREP] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCIONREP] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPARTIDOR] ADD CONSTRAINT [PK_REPARTIDOR] PRIMARY KEY CLUSTERED  ([IDREPARTIDOR]) ON [PRIMARY]
GO
